### ISSUE TITLE
It pastes the command instead of the output of the command

### ISSUE THREAD

**Issue by d3vv3** [seqizz/ulauncher-password-store#4]
The extension pastes "pass show -c <folder>/<file>" instead of the content.

**Comment by seqizz** [comment]
Hi, thanks for the report. But I couldn't reproduce the issue. When I select a pass entry with enter and paste somewhere I get the password. Could you give an example which action you are referring to? (Or do you want whole content to be pasted instead of first line?)

**Comment by d3vv3** [comment]
For example: 
Ctrl+Space; pass Sites/amazon; Ctrl+V
As a result, sometimes I get "pass show -c Sites/amazon" and sometimes I get the password copied.
So it doesn't even ask me for the GPG password because the command is not executing, it's only copying the command. Thanks for your reply!

**Comment by seqizz** [comment]
I guess I understood the problem. Latest commit should fix the issue. Please update (or if it fails re-install) the plugin to check and please don't hesitate to re-open if still continues.
